version: '3.7'
services: 
  db:
    image: mariadb:10.5.8
    container_name: db
    restart: unless-stopped
    tty: true
    ports: 
      - "6603:3306"
    volumes: 
      - ./docker-compose/mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./docker-comopse/mariadb/data/:/var/lib/mysql/
    environment: 
      MYSQL_ROOT_PASSWORD: admins

  pma:
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports: 
      - '8080:80'
    environment: 
      PMA_HOST: db
